BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb_ok3568c"
BBFILE_PATTERN_evb_ok3568c = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_ok3568c = "1"

LAYERSERIES_COMPAT_evb_ok3568c = "whinlatter walnascar"