#@TYPE: Machine
#@NAME: EVB RaspberryPi 4B (64bit)
#@DESCRIPTION: OpenBMC EVB machine configuration for RaspberryPi 4 Model B in 64-bit mode

require conf/machine/raspberrypi4-64.conf

# Limit the EVB machine to the Raspberry Pi 4 Model B device tree.
RPI_KERNEL_DEVICETREE = "broadcom/bcm2711-rpi-4-b.dtb"

# RPi4 kernel deploy does not produce fitImage; use linux.bin for MMC tar image assembly.
FLASH_KERNEL_IMAGE = "linux.bin"

include conf/machine/include/obmc-evb-common.inc
include conf/machine/include/evb-rpi-camera-common.inc
