BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb_raspberry4b"
BBFILE_PATTERN_evb_raspberry4b = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_raspberry4b = "1"

LAYERSERIES_COMPAT_evb_raspberry4b = "whinlatter walnascar"
