BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb_common"
BBFILE_PATTERN_evb_common = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_common = "1"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

LAYERSERIES_COMPAT_evb_common = "whinlatter walnascar"